version: '3.4'

services:

##################################################################################
## Cluster PEER 0 ################################################################
##################################################################################

  ipfs0:
    container_name: ipfs0
    image: ipfs-local
#   ports:
#     - "4001:4001" # ipfs swarm - expose if needed/wanted
#     - "5001:5001" # ipfs api - expose if needed/wanted
#     - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ipfs0-data:/data/ipfs
  
  ipns_gateway:
    container_name: ipns_gateway
    image: ipns-gateway-local
    depends_on:
      - ipfs0
    # environment:
    #   CLUSTER_PEERNAME: cluster0
    #   CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
    #   CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
    #   CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
    #   CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
    #   CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
          - "8888:8888"
    volumes:
      - ${PWD}:/work
      - ipfs0-data:/ipfs0_data
volumes:
  ipfs0-data: