# author - S@M
version: '3.4'

services:
  ipfs:
    image: ipfs-local
    container_name: ipfs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ipfs0-data:/config
    ports:
#      - 80:80
      - 4001:4001
      - 5001:5001
      - 8080:8080
#      - 443:443 #optional
    restart: unless-stopped
      
  ipns_gateway:
    container_name: ipns_gateway
    image: ipns-gateway-local
    depends_on:
      - ipfs
    ports:
          - "8888:8888"
    volumes:
      - ${PWD}:/work
      - ipfs0-data:/ipfs0_data
#    restart: unless-stopped
#    command: sh
volumes:
  ipfs0-data:
