FROM alpine as ipfs-runtime
WORKDIR /work
COPY ./ipfs /work

# Swarm TCP; should be exposed to the public
EXPOSE 4001
# Swarm UDP; should be exposed to the public
EXPOSE 4001/udp
# Daemon API; must not be exposed publicly but to client services under you control
EXPOSE 5001
# Web Gateway; can be exposed publicly with a proxy, e.g. as https://ipfs.example.org
EXPOSE 8080
# Swarm Websockets; must be exposed publicly when the node is listening using the websocket transport (/ipX/.../tcp/8081/ws).
EXPOSE 8081

#CMD ./ipfs init

#docker build --target ipfs-runtime . -t ipfs-local
#docker run -it -p 4001:4001 -p 5001:5001 -p 8088:8080 -p 8089:8081 ipfs-local