FROM alpine as ipfs-runtime

RUN apk update \
    && apk fetch gnupg \
    && apk add gnupg \
    && gpg --list-keys

WORKDIR /work
COPY ./ipfs /bin
COPY ./ipfs_init /work
RUN chmod 0755 /work/ipfs_init

# Swarm TCP; should be exposed to the public
EXPOSE 4001
# Swarm UDP; should be exposed to the public
EXPOSE 4001/udp
# Daemon API; must not be exposed publicly but to client services under you control
EXPOSE 5001
# Web Gateway; can be exposed publicly with a proxy, e.g. as https://ipfs.example.org
EXPOSE 8080
# Swarm Websockets; must be exposed publicly when the node is listening using the websocket transport (/ipX/.../tcp/8081/ws).
EXPOSE 8081

ENV version=1.0.7
ENV version=1.0.7
ENV IPFS_PATH="/work/.ipfs"
ENV cache_dir="${IPFS_PATH}/.cache"
ENV GNUPGHOME="${IPFS_PATH}/.gpg"
ENV sockets="${IPFS_PATH}/.sockets"
ENV pid_file="${IPFS_PATH}/.pid"
ENV ipfs_subd_gw="${IPFS_SUBD_GW:-https://cf-ipfs.com}" 
ENV ipfs_path_gw="${IPFS_PATH_GW:-https://ipfs.io}"
ENV blacklist_file="${IPFS_PATH}/blacklist.txt"

RUN ./ipfs_init

#docker build --target ipfs-runtime . -t ipfs-local
#docker run -it -p 4001:4001 -p 5001:5001 -p 8088:8080 -p 8089:8081 ipfs-local sh
#docker exec "container name" ipfs daemon --enable-namesys-pubsub --enable-gc
#docker exec "container name" ipfs swarm peers